// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUta-D6kcybIKCTYw7EgSfLcHDnVk9ikI',
    appId: '1:462364602665:web:d16f5a6c55ffa12dcb8738',
    messagingSenderId: '462364602665',
    projectId: 'controlgastos-9c448',
    authDomain: 'controlgastos-9c448.firebaseapp.com',
    storageBucket: 'controlgastos-9c448.appspot.com',
    measurementId: 'G-7PBRS2YW9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUST1W2aU9BzmHF1gsIEg5zb5Az7uaUu0',
    appId: '1:462364602665:android:6baedfc8ecd3bb3ccb8738',
    messagingSenderId: '462364602665',
    projectId: 'controlgastos-9c448',
    storageBucket: 'controlgastos-9c448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87cXTIZTB8SDVoykUWq7L0Ynl56kV9wo',
    appId: '1:462364602665:ios:a129d171f2f15f85cb8738',
    messagingSenderId: '462364602665',
    projectId: 'controlgastos-9c448',
    storageBucket: 'controlgastos-9c448.appspot.com',
    iosClientId: '462364602665-7knaja6d7i875gnhd039ocf9u7tpanet.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlGastos1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87cXTIZTB8SDVoykUWq7L0Ynl56kV9wo',
    appId: '1:462364602665:ios:6738e32f22d44b85cb8738',
    messagingSenderId: '462364602665',
    projectId: 'controlgastos-9c448',
    storageBucket: 'controlgastos-9c448.appspot.com',
    iosClientId: '462364602665-ah2ld5p4dqg1n464jlf810b41idueenr.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlGastos1.RunnerTests',
  );
}
